export const testData =  {
    validTestData : { 

    first_name : "Ivan",
	valid_first_name_1_character :"J",
	valid_first_name_64_characters :'JohnMichaelRaymondKristopherGeorgeRobertDerickJeffryAbelHarryJob',
	last_name: "Belik",
	valid_last_name_1_character: "A",
	valid_last_name_64_characters: "AllenBooneCaldwellLittleWilcoxHenryArmstrongPattersonNashSpencer",
	corporate_name:"Padawans",
	valid_corporate_name_1_character:"P",
	valid_corporate_name_64_characters:"PadawansPadawansPadawansPadawansPadawansPadawansPadawansPadawans",
	number_of_users: "100500",
	user_1: "1",
	users_100000000: "100000000",
	users_1000000001: "1000000001",
	work_email: "onlitest@mail.ru",
	valid_value_email_64_characters: "PadawansPadawansPadawansPadawansPadawansPadawansPadawansPadaw@ru",
	phone_number: "88007777777",
	phone_number_1_character: "8",
	phone_number_64_characters: "8800777777788007777777880077777778800777777788077777778007777777",
	comments: "Vadim's Padawans are the best of the best! This is a test post!",
	valid_comments_1_character: "Y",
	valid_comments_2000_characters: "dfghfngggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffffffffffffffffffffffdfghfngggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffffffffffffffffffffffdfghfngggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffffffffffffffffffffffdfghfngggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffffffffffffffffffffffdfghfngggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffffffffffffffffffffffdfghfngggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfffffffgggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffffffffffffffffffffffdfghfngggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffffffffffffffffffffffdfghfngggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffffffffffffffffffffffdddddddddddddddddgggggggg"
 },

 notValidTestData : { 
	not_valid_first_name_65_characters:"JohnMichaelRaymondKristopherGeorgeRobertDerickJeffryAbelHarryJobb",
	not_valid_last_name_65_characters: "AllenBooneCaldwellLittleWilcoxHenryArmstrongPattersonNashSpencerr",
	not_valid_corporate_name_65_characters:"PadawansPadawansPadawansPadawansPadawansPadawansPadawansPadawanss",
	negative_number_of_users: "-100500",
	not_an_integer: "100.500",
	not_valid_worked_email_on_1_character:"@",
	not_valid_value_email_65_characters: "PadawansPadawansPadawansPadawansPadawansPadawansPadawansPadawa@ru",
	email_not_validation_worked_on_72_characters:"PadawansPadawansPadawansPadawansPadawansPadawansPadawansPadawansPadaw@ru",
	email_validation_worked_on_73_characters:"PadawansPadawansPadawansPadawansPadawansPadawansPadawansPadawansPadawa@ru",
	phone_number_65_characters: "88007777777880077777778800777767778800777777788077777778007777777",
	not_valid_value_comments_2001_characters:"dfghfngggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffffffffffffffffffffffdfghfngggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffffffffffffffffffffffdfghfngggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffffffffffffffffffffffdfghfngggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffffffffffffffffffffffdfghfngggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffffffffffffffffffffffdfghfngggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmfffffffgggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffffffffffffffffffffffdfghfngggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffffffffffffffffffffffdfghfngggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggdggggggbccffffffffffffffoooooooooooooooooooooccccccccccccccccccccccccccccmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffffffffffffffffffffffdddddddddddddddddggggggggg",
	
 }
}